version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /contact.html
    destination: /var/www/html
  - source: /css
    destination: /var/www/html/
  - source: /images/
    destination: /var/www/html/
    
    
 
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
